-- S-001: レシート明細テーブル（receipt）から全項目の先頭10件を表示し、どのようなデータを保有しているか目視で確認せよ。

config {
        type: "table",
        database: "test-dataform-395505",
        schema: "mart",
        name: "s001",
        tags: ["mart"],
        }
 
SELECT
    sd.*,
    customer_id,
    purchase_amount,
    CURRENT_TIMESTAMP AS mart_s001_timestamp
FROM
    ${ref("store_sales_data")} AS sd
LEFT JOIN
    ${ref("customer_purchase_amount")} As ca
    ON sd.store_cd = ca.store_cd