-- S-003: レシート明細のテーブル（receipt）から売上日（sales_ymd）、顧客ID（customer_id）、商品コード（product_cd）、売上金額（amount）の順に列を指定し、10件表示させよ。ただし、sales_ymdはsales_dateに項目名を変更しながら抽出すること。

config {
        type: "table",
        database: "test-dataform-395505",
        schema: "mart",
        name: "s003"
        }

SELECT sales_ymd AS sales_date,
        customer_id,
        product_cd,
        amount,
        CURRENT_TIMESTAMP AS mart_s002_timestamp
FROM `new-100-knocks.100knocks.receipt`
LIMIT 10