config {
        type: "incremental",
        database: "test-dataform-395505",
        schema: "warehouse", 
        name: "store_sales_data_2",
        tags: ["warehouse"],
        dependencies: [ "receipt", "store" ],
        protected: true,
        }

MERGE INTO ${ref('store_sales_data')} AS target
USING (

  WITH store_amount_tb AS (
    SELECT 
      COUNT(customer_id) AS costomer_num,
      SUM(amount) AS store_amount,
      store_cd
  FROM
    ${ref('receipt')}
  GROUP BY store_cd

  )
  
  SELECT
    store.store_cd,
    store_name,
    store_amount,
    costomer_num
  FROM
    ${ref('store')} as store
  LEFT JOIN
    store_amount_tb
    ON store.store_cd = store_amount_tb.store_cd

) AS source
ON target.store_cd = source.store_cd

WHEN MATCHED THEN
  UPDATE SET 
    target.costomer_num = source.costomer_num,
    target.store_amount = source.store_amount

WHEN NOT MATCHED THEN
  INSERT (store_cd, store_name, store_amount, costomer_num)
  VALUES(source.store_cd, source.store_name, source.store_amount, source.costomer_num)